#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use App\Commands\ListCourses;
use App\Commands\listAssignments;
use App\Commands\ListStudents;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new ListCourses());
$application->add(new ListStudents());
$application->add(new listAssignments());

$application->run();
